// Copyright (C) 2026 Mikko Parkkola. All rights reserved.
// Licensed under AGPL-3.0. See LICENSE file.

package report

import (
	"encoding/json"
	"strings"
	"testing"

	"github.com/MikkoParkkola/nowifi/internal/bypass"
	"github.com/MikkoParkkola/nowifi/internal/tunnel"
)

// ---------------------------------------------------------------------------
// Helpers to build test fixtures
// ---------------------------------------------------------------------------

func samplePortal() PortalInfo {
	return PortalInfo{
		IsCaptive:   true,
		PortalType:  "http_redirect",
		Vendor:      "Aruba",
		SSID:        "TestNet",
		Gateway:     "192.168.1.1",
		PortalURL:   "http://portal.example.com/login",
		AuthMethods: []string{"click-through", "email"},
	}
}

func sampleProbes() ProbeResults {
	return ProbeResults{
		DNS:        ProbeResult{IsOpen: true, Details: "UDP/53 open to 8.8.8.8"},
		ICMP:       ProbeResult{IsOpen: false, Details: "ping blocked"},
		IPv6:       ProbeResult{IsOpen: true, Details: "Global IPv6 available"},
		Cloudflare: ProbeResult{IsOpen: true, Details: "1.1.1.1:443 reachable"},
		QUIC:       ProbeResult{IsOpen: false, Details: "UDP/443 blocked"},
		NTP:        ProbeResult{IsOpen: true, Details: "UDP/123 open"},
		DoH:        ProbeResult{IsOpen: false, Details: "DoH blocked"},
		Whitelists: []WhitelistResult{
			{Domain: "apple.com", IsOpen: true, Details: "whitelisted"},
		},
		OpenPorts: []PortResult{
			{Port: 80, Service: "http", IsOpen: true},
			{Port: 443, Service: "https", IsOpen: true},
			{Port: 22, Service: "ssh", IsOpen: false},
		},
	}
}

func sampleBypasses() []bypass.Result {
	return []bypass.Result{
		{
			Method:      bypass.IPv6Bypass,
			Success:     true,
			Severity:    "critical",
			Impact:      "Full IPv6 internet",
			Details:     "Global IPv6 available",
			Remediation: "Apply IPv6 ACLs",
		},
		{
			Method:  bypass.ChiselTunnel,
			Success: false,
			Details: "No tunnel server",
		},
	}
}

func emptyBypasses() []bypass.Result {
	return []bypass.Result{
		{Method: bypass.IPv6Bypass, Success: false, Details: "no IPv6"},
		{Method: bypass.ChiselTunnel, Success: false, Details: "no server"},
	}
}

// ---------------------------------------------------------------------------
// Test: PrintTerminal doesn't panic with valid data
// ---------------------------------------------------------------------------

func TestPrintTerminal_ValidData(t *testing.T) {
	// PrintTerminal writes to stdout; we just verify no panic.
	defer func() {
		if r := recover(); r != nil {
			t.Fatalf("PrintTerminal panicked: %v", r)
		}
	}()

	PrintTerminal(samplePortal(), sampleProbes(), sampleBypasses())
}

// ---------------------------------------------------------------------------
// Test: PrintTerminal doesn't panic with empty data
// ---------------------------------------------------------------------------

func TestPrintTerminal_EmptyData(t *testing.T) {
	defer func() {
		if r := recover(); r != nil {
			t.Fatalf("PrintTerminal panicked with empty data: %v", r)
		}
	}()

	PrintTerminal(PortalInfo{}, ProbeResults{}, nil)
}

// ---------------------------------------------------------------------------
// Test: PrintTerminal with active tunnel
// ---------------------------------------------------------------------------

func TestPrintTerminal_ActiveTunnel(t *testing.T) {
	defer func() {
		if r := recover(); r != nil {
			t.Fatalf("PrintTerminal panicked with tunnel: %v", r)
		}
	}()

	bypasses := []bypass.Result{
		{
			Method:  bypass.ChiselTunnel,
			Success: true,
			Tunnel:  &tunnel.Handle{Active: true, LocalPort: 1080, Method: "chisel"},
		},
	}
	PrintTerminal(samplePortal(), sampleProbes(), bypasses)
}

// ---------------------------------------------------------------------------
// Test: GenerateMarkdown contains expected sections
// ---------------------------------------------------------------------------

func TestGenerateMarkdown_ContainsSections(t *testing.T) {
	md := GenerateMarkdown(samplePortal(), sampleProbes(), sampleBypasses())

	sections := []string{
		"# Captive Portal Security Assessment Report",
		"## Leak Enumeration",
		"## Bypass Results",
		"## Findings & Remediation",
		"Generated by nowifi",
	}
	for _, s := range sections {
		if !strings.Contains(md, s) {
			t.Errorf("markdown missing section: %q", s)
		}
	}
}

// ---------------------------------------------------------------------------
// Test: GenerateMarkdown contains portal info
// ---------------------------------------------------------------------------

func TestGenerateMarkdown_ContainsPortalInfo(t *testing.T) {
	md := GenerateMarkdown(samplePortal(), sampleProbes(), sampleBypasses())

	fields := []string{
		"TestNet",
		"192.168.1.1",
		"Aruba",
		"http_redirect",
	}
	for _, f := range fields {
		if !strings.Contains(md, f) {
			t.Errorf("markdown missing portal field: %q", f)
		}
	}
}

// ---------------------------------------------------------------------------
// Test: GenerateMarkdown with no successful bypasses
// ---------------------------------------------------------------------------

func TestGenerateMarkdown_NoFindings(t *testing.T) {
	md := GenerateMarkdown(samplePortal(), sampleProbes(), emptyBypasses())

	if strings.Contains(md, "## Findings & Remediation") {
		t.Error("markdown should NOT contain Findings section when no bypasses succeeded")
	}
	if !strings.Contains(md, "## Bypass Results") {
		t.Error("markdown should still contain Bypass Results section")
	}
}

// ---------------------------------------------------------------------------
// Test: GenerateMarkdown contains probe protocols
// ---------------------------------------------------------------------------

func TestGenerateMarkdown_ProbeProtocols(t *testing.T) {
	md := GenerateMarkdown(samplePortal(), sampleProbes(), sampleBypasses())

	protocols := []string{
		"DNS (UDP/53)",
		"ICMP",
		"IPv6",
		"HTTPS (CF)",
		"QUIC (UDP/443)",
		"NTP (UDP/123)",
		"DoH (HTTPS)",
	}
	for _, p := range protocols {
		if !strings.Contains(md, p) {
			t.Errorf("markdown missing protocol: %q", p)
		}
	}
}

// ---------------------------------------------------------------------------
// Test: GenerateMarkdown whitelisted domains
// ---------------------------------------------------------------------------

func TestGenerateMarkdown_Whitelists(t *testing.T) {
	md := GenerateMarkdown(samplePortal(), sampleProbes(), sampleBypasses())

	if !strings.Contains(md, "apple.com") {
		t.Error("markdown missing whitelisted domain apple.com")
	}
}

// ---------------------------------------------------------------------------
// Test: GenerateJSON is valid JSON
// ---------------------------------------------------------------------------

func TestGenerateJSON_ValidJSON(t *testing.T) {
	jsonStr := GenerateJSON(samplePortal(), sampleProbes(), sampleBypasses())

	var raw map[string]interface{}
	if err := json.Unmarshal([]byte(jsonStr), &raw); err != nil {
		t.Fatalf("GenerateJSON produced invalid JSON: %v\n%s", err, jsonStr)
	}
}

// ---------------------------------------------------------------------------
// Test: GenerateJSON contains all fields
// ---------------------------------------------------------------------------

func TestGenerateJSON_ContainsAllFields(t *testing.T) {
	jsonStr := GenerateJSON(samplePortal(), sampleProbes(), sampleBypasses())

	var report jsonReport
	if err := json.Unmarshal([]byte(jsonStr), &report); err != nil {
		t.Fatalf("JSON unmarshal failed: %v", err)
	}

	tests := []struct {
		name string
		ok   bool
	}{
		{"timestamp non-empty", report.Timestamp != ""},
		{"portal.is_captive", report.Portal.IsCaptive},
		{"portal.type", report.Portal.Type == "http_redirect"},
		{"portal.vendor", report.Portal.Vendor == "Aruba"},
		{"portal.ssid", report.Portal.SSID == "TestNet"},
		{"portal.gateway", report.Portal.Gateway == "192.168.1.1"},
		{"portal.url", report.Portal.URL == "http://portal.example.com/login"},
		{"portal.auth_methods len", len(report.Portal.AuthMethods) == 2},
		{"probes.dns.open", report.Probes.DNS.Open},
		{"probes.icmp.open false", !report.Probes.ICMP.Open},
		{"probes.ipv6.open", report.Probes.IPv6.Open},
		{"probes.cloudflare.open", report.Probes.Cloudflare.Open},
		{"probes.quic.open false", !report.Probes.QUIC.Open},
		{"probes.ntp.open", report.Probes.NTP.Open},
		{"probes.doh.open false", !report.Probes.DoH.Open},
		{"whitelists len", len(report.Probes.Whitelists) == 1},
		{"open_ports len", len(report.Probes.OpenPorts) == 2}, // 2 open out of 3
		{"bypasses len", len(report.Bypasses) == 2},
		{"bypass[0] success", report.Bypasses[0].Success},
		{"bypass[1] not success", !report.Bypasses[1].Success},
	}

	for _, tc := range tests {
		t.Run(tc.name, func(t *testing.T) {
			if !tc.ok {
				t.Errorf("check failed: %s", tc.name)
			}
		})
	}
}

// ---------------------------------------------------------------------------
// Test: GenerateJSON with empty data
// ---------------------------------------------------------------------------

func TestGenerateJSON_EmptyData(t *testing.T) {
	jsonStr := GenerateJSON(PortalInfo{}, ProbeResults{}, nil)

	var raw map[string]interface{}
	if err := json.Unmarshal([]byte(jsonStr), &raw); err != nil {
		t.Fatalf("GenerateJSON with empty data produced invalid JSON: %v", err)
	}
	if _, ok := raw["timestamp"]; !ok {
		t.Error("JSON missing timestamp field")
	}
	if _, ok := raw["portal"]; !ok {
		t.Error("JSON missing portal field")
	}
}

// ---------------------------------------------------------------------------
// Test: stripANSI helper
// ---------------------------------------------------------------------------

func TestStripANSI(t *testing.T) {
	tests := []struct {
		name  string
		input string
		want  string
	}{
		{"plain text", "hello", "hello"},
		{"with color", "\033[31mred\033[0m", "red"},
		{"bold+color", "\033[1;31mCRIT\033[0m", "CRIT"},
		{"empty", "", ""},
		{"no escape", "no escape here", "no escape here"},
	}
	for _, tc := range tests {
		t.Run(tc.name, func(t *testing.T) {
			got := stripANSI(tc.input)
			if got != tc.want {
				t.Errorf("stripANSI(%q) = %q, want %q", tc.input, got, tc.want)
			}
		})
	}
}

func TestRenderTerminalOutput_ColorDisabled(t *testing.T) {
	orig := colorEnabled
	t.Cleanup(func() { colorEnabled = orig })
	colorEnabled = false

	got := renderTerminalOutput(red + "HIGH" + reset)
	if got != "HIGH" {
		t.Fatalf("renderTerminalOutput() = %q, want HIGH", got)
	}
	if strings.Contains(got, "\033") {
		t.Fatalf("renderTerminalOutput() retained ANSI escape: %q", got)
	}
}

// ---------------------------------------------------------------------------
// Test: nvl helper
// ---------------------------------------------------------------------------

func TestNvl(t *testing.T) {
	tests := []struct {
		val, fallback, want string
	}{
		{"hello", "default", "hello"},
		{"", "default", "default"},
		{"", "", ""},
		{"a", "", "a"},
	}
	for _, tc := range tests {
		got := nvl(tc.val, tc.fallback)
		if got != tc.want {
			t.Errorf("nvl(%q, %q) = %q, want %q", tc.val, tc.fallback, got, tc.want)
		}
	}
}

// ---------------------------------------------------------------------------
// Test: severityTag and severityColor
// ---------------------------------------------------------------------------

func TestSeverityTag(t *testing.T) {
	tags := []struct {
		sev  string
		want string
	}{
		{"critical", "CRIT"},
		{"high", "HIGH"},
		{"medium", "MED"},
		{"low", "LOW"},
		{"info", "INFO"},
		{"unknown", "?"},
	}
	for _, tc := range tags {
		t.Run(tc.sev, func(t *testing.T) {
			got := stripANSI(severityTag(tc.sev))
			if got != tc.want {
				t.Errorf("severityTag(%q) stripped = %q, want %q", tc.sev, got, tc.want)
			}
		})
	}
}

// ---------------------------------------------------------------------------
// Test: boolIcon and successIcon
// ---------------------------------------------------------------------------

func TestBoolIcon(t *testing.T) {
	openIcon := stripANSI(boolIcon(true))
	if openIcon != "OPEN" {
		t.Errorf("boolIcon(true) = %q, want OPEN", openIcon)
	}
	closedIcon := stripANSI(boolIcon(false))
	if closedIcon != "CLOSED" {
		t.Errorf("boolIcon(false) = %q, want CLOSED", closedIcon)
	}
}

func TestSuccessIcon(t *testing.T) {
	okIcon := stripANSI(successIcon(true))
	if okIcon != "SUCCESS" {
		t.Errorf("successIcon(true) = %q, want SUCCESS", okIcon)
	}
	failIcon := stripANSI(successIcon(false))
	if failIcon != "failed" {
		t.Errorf("successIcon(false) = %q, want failed", failIcon)
	}
}

// ---------------------------------------------------------------------------
// Test: drawBox doesn't panic
// ---------------------------------------------------------------------------

func TestDrawBox(t *testing.T) {
	result := drawBox("Title", cyan, "line1\nline2\nline3")
	if result == "" {
		t.Error("drawBox returned empty string")
	}
	if !strings.Contains(result, "Title") {
		t.Error("drawBox result missing title")
	}
}

// ---------------------------------------------------------------------------
// Test: simpleTable doesn't panic
// ---------------------------------------------------------------------------

func TestSimpleTable(t *testing.T) {
	result := simpleTable("Test Table", cyan,
		[]string{"Col1", "Col2"},
		[][]string{{"a", "b"}, {"c", "d"}},
	)
	if result == "" {
		t.Error("simpleTable returned empty string")
	}
	if !strings.Contains(result, "Test Table") {
		t.Error("simpleTable result missing title")
	}
}
